# Generated by Django 3.2.12 on 2022-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_up',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
