# Generated by Django 3.2.12 on 2022-06-06 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_up',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
