# Generated by Django 3.2.12 on 2022-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='avatar/avatarDefault.png', upload_to='avatar'),
        ),
    ]
