# Generated by Django 3.2.12 on 2022-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatarDefault.png', null=True, upload_to='avatar'),
        ),
    ]
